### ISSUE TITLE
启动mac os 13 beta6，会出错，可以处理下吗？

### ISSUE THREAD

**Issue by pureimagine** [zty199/HP_Pavilion_15-cb073tx_Hackintosh#11]
启动mac os 13 beta6，会出现AICP Error :Method parse/execut failed SB.AC.ADJP.需要怎么解决这个问题呢？
![IMG_1039](https://user-images.githubusercontent.com/28209291/233686584-c3e15efa-26a5-48e7-949c-97de6211a1f4.JPG)

**Comment by pureimagine** [comment]
然后会进入进度条，但是会卡在哪里

**Comment by zty199** [comment]
电脑已经约等于寿终正寝了，很久没维护了......抱歉
