### ISSUE TITLE
升级到 13.4.1 后偶尔会出现嘟嘟嘟。。。的连续响声

### ISSUE THREAD

**Issue by isfong** [zty199/HP_Pavilion_15-cb073tx_Hackintosh#12]
如题，听到这种连续声音后打开应用启动台，或者命令行 总之就是存在光标闪烁带输入框的界面，发现竟然在连续不断的输入字符 `////////////.....` ，只能按下esc键才会停止，过一会不经意间又会发生这种情况， 真是哭笑不得，然后我自己升级适配到oc 0.9.x 这种情况消失，但是蓝牙又无法驱动了

**Comment by zty199** [comment]
电脑已经约等于寿终正寝了，很久没维护了......抱歉
