### ISSUE TITLE
type-c 

### ISSUE THREAD

**Issue by luojasonlee** [zty199/HP_Pavilion_15-cb073tx_Hackintosh#3]
Output display black screen

**Comment by zty199** [comment]
Make sure you are using the same model as mine......
It works on my device...... I'm using a Type-C to HDMI adapter and it works fine before macOS Big Sur 11.5......
For now I have just sold my external display, so I haven't test that in new version yet.

**Comment by luojasonlee** [comment]
Mine is a 2K Samsung monitor, which can display pictures after adjustment, but occasionally the screen is broken, and even the monitor can only display for a period of time after it is turned on.
