### ISSUE TITLE
Can WiFi and NVIDIA GeForce GTX 1050 be connected?

### ISSUE THREAD

**Issue by Stud-pro** [zty199/HP_Pavilion_15-cb073tx_Hackintosh#4]
Your build fit great for my HP Pavilion Power 15 cb007ur model. Installation and launches are going well, only a number of difficulties arose:
- WiFi - it is turned on, but does not see the networks themselves, maybe some settings need to be made or kext added?
- NVIDIA GeForce GTX 1050 - can I run it, just can't install After Effects, and it slows down during boot, can it be connected?

**Comment by zty199** [comment]
1. About WiFi - If you didn't replace your original WiFi card, it should be Intel 7265AC? You can just use itlwm and IntelBluetoothFirmware to get it work.
[OpenIntelWireless/itlwm](https://github.com/OpenIntelWireless/itlwm)
[OpenIntelWireless/IntelBluetoothFirmware](https://github.com/OpenIntelWireless/IntelBluetoothFirmware)

2. There is no way to make GTX 1050 work in ANY version of macOS, even in 10.12 and 10.13...... So don't count on it, I just disabled it in SSDT and WhateverGreen device-properties.
