### ISSUE TITLE
大佬，那个EC寻找风扇偏移地址到底怎么做

### ISSUE THREAD

**Issue by mjs520** [zty199/HP_Pavilion_15-cb073tx_Hackintosh#5]
我看了您发的内容，没看懂，具体怎么通过哪些驱动，然后是在终端要什么命令，还有怎么看数据，DSDT里面的ERAM，我看你们截图，似乎偏移量不是从里面找的，因为我看你最终选取的DSDT下的ERAM里面没有那个数，大佬可以远景论坛出个具体教程吗，谢谢

**Comment by mjs520** [comment]
1

**Comment by zGzARY** [comment]
你可能发错人了 我并不会做这个

从 Windows 版邮件发送

发件人: mjs520
发送时间: 2021年9月1日 19:55
收件人: zty199/HP_Pavilion_15-cb073tx_Hackintosh
抄送: Subscribed
主题: Re: [zty199/HP_Pavilion_15-cb073tx_Hackintosh] 大佬，那个EC寻找风扇偏移地址到底怎么做 (#5)

1
