### ISSUE TITLE
安装monterey 无限循环 macosInsaller 启动项

### ISSUE THREAD

**Issue by isfong** [zty199/HP_Pavilion_15-cb073tx_Hackintosh#8]
#### 我的电脑信息：
- 惠普PAVILION 15-CB076TX(2FL09PA)
- CPU  i7 7700HQ
- 内存 16G DDR4
- 显卡 GTX 1050ti
- 固态256G 装有windows10, MacOS 用的机械 1T 盘格式化APPFS + GUID 后开始安装的， 用的是你目前Master分支的OC EFI

**Comment by zty199** [comment]
测试下 OC 0.8.4，昨晚上更新的。我这里很久没有测试过全新安装了......

**Comment by isfong** [comment]
> 测试下 OC 0.8.4，昨晚上更新的。我这里很久没有测试过全新安装了......

感谢大佬的EFI😘，问题已经绕过，我先用你的Clover安装完系统，再修改实际EFI为OC即可，额外再加上IntelWiFi 和蓝牙驱动，现在非常完美的黑macbook pro！0.8.4已经测试引导开关机机各项驱动都正常，再次感谢！！！！

**Comment by isfong** [comment]
> > 测试下 OC 0.8.4，昨晚上更新的。我这里很久没有测试过全新安装了......
> 
> 感谢大佬的EFI😘，问题已经绕过，我先用你的Clover安装完系统，再修改实际EFI为OC即可，额外再加上IntelWiFi 和蓝牙驱动，现在非常完美的黑macbook pro！0.8.4已经测试引导开关机机各项驱动都正常，再次感谢！！！！

0.8.4我也没有测试全新安装，不知道还有没有循环installer的问题

**Comment by zty199** [comment]
目前测试，Monterey 升级 Ventura 正常，暂时不测试全新安装了......太费时间了
