### ISSUE TITLE
请问opencore如何修复从windows重启没有声音的？

### ISSUE THREAD

**Issue by ahaolee** [zty199/HP_Pavilion_15-cb073tx_Hackintosh#9]
> 修复了从 Windows 系统重启后进入其他系统（如 Linux，macOS 等）扬声器没有声音的问题（感谢OC交流群大佬 @哞 @常原）。

请问关于此修复描述，采用的是何种解决办法？盼回复，谢谢带佬！

**Comment by zty199** [comment]
我记得当时大佬们教我们用 APCI patch 修改了一个原生 SSDT，把重启行为从热重启改成了冷重启（重启过程中会断电，表现和关机再开机一样）。扬声器在断电后启动是正常的。

[https://github.com/zty199/HP_Pavilion_15-cb073tx_Hackintosh/blob/9bac0dd1c9ee015b0fec1c634978a053b2170903/EFI_OC/OC/config.plist#L293-L322](https://github.com/zty199/HP_Pavilion_15-cb073tx_Hackintosh/blob/9bac0dd1c9ee015b0fec1c634978a053b2170903/EFI_OC/OC/config.plist#L293-L322)
